<div id="humm_payment_info">
        <img src="<?php echo Mage::getDesign()->getSkinUrl( "images/Humm/humm-logo.png" ) ?>"
             style="width:auto;height:30px;"/>
</div>
<style type="text/css">
#humm_payment_info img {
    height: 36px;
    vertical-align: middle;
    padding: 5px 0;
    display: inline-block;
    line-height: 26px;
    margin-right: 5px;
}
#humm_payment_info > span {
    display: inline-block;
    line-height: 26px;
    padding: 5px 0;
}
</style>
