<!--Humm Logo-->
<div>
    <?php
    $launch_time_string = Mage::getStoreConfig( 'payment/humm_payments/launch_time_string' );
    $is_after           = ( time() - strtotime( $launch_time_string ) >= 0 ) || Mage::getStoreConfig( 'payment/humm_payments/force_humm' );
    if ( $is_after || Mage::getStoreConfig( 'payment/humm_payments/country_currency/specific_countries' ) == 'AU' ) {
        ?>
        <img src="<?php echo Mage::getDesign()->getSkinUrl( "images/Humm/humm-logo.png" ) ?>"
             style="width:auto;height:20px;margin-right:10px;"/>
        <?php
    } else {
        ?>
        <img src="<?php echo Mage::getDesign()->getSkinUrl( "images/Humm/oxipay-logo.png" ) ?>"
             style="width:auto;height:24px;margin-right:10px;"/>
        <?php
    }
    ?>
</div>