<?php
if (!$this->isActive()) {
    return;
}
$country = $this->getCountry();

if ($country == "AU") {
    if (!strcmp($this->getWidgetPageType(), 'product')) {
        $productPrice = $this->getProduct();
        $jsScript = sprintf("%s%s%s", '<script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=', $productPrice, '&LittleOnly&element=%23messages_product_view"></script>');
        echo $jsScript;
    }

    if (!strcmp($this->getWidgetPageType(), 'cart')) {
        $cartPrice = $this->getCart();
        $jsCart = sprintf("%s%s%s", '<script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=', $cartPrice, '&LittleOnly&element=%23shopping-cart-totals-table"></script>');
        echo $jsCart;
    }
}

if ($country == "NZ") {
    if (!strcmp($this->getWidgetPageType(), 'product')) {
        $productPrice = $this->getProduct();
        if (floatval($productPrice) <1000) {
            $jsScript = sprintf("%s%s%s", '<script src="https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '&LittleThings&little=F5&element=%23messages_product_view"></script>');
            $jsScript = $jsScript . sprintf("%s%s%s", '<script src="https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '&LittleThings&little=w10&element=%23messages_product_view"></script>');
            echo $jsScript;
        }
        else
        {
            $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '&big=M6', '&element=%23messages_product_view"></script>');
            echo $ec_pattern;
        }

    }

    if (!strcmp($this->getWidgetPageType(), 'cart')) {
        $cartPrice = $this->getCart();
        if (floatval($cartPrice) < 1000) {
            $jsCart = sprintf("%s%s%s", '<script src="https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $cartPrice, '&LittleThings&little=F5&element=%23shopping-cart-totals-table"></script>');
            $jsCart = $jsCart . sprintf("%s%s%s", '<script src="https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $cartPrice, '&LittleThings&little=w10&element=%23shopping-cart-totals-table"></script>');
            echo $jsCart;
        }
        else {
            $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $cartPrice, '&big=M6', '&element=%2Ecart-totals"></script>');
            echo $ec_pattern;
        }
    }
}
